config/routes.rb
Rails.application.routes.draw do
    root 'posts#index', as: 'home'
    get 'about' => 'pages#about', as: 'about'
    resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about 
        @title = 'About This Project'
        @content = 'Simply getting back into practice with Ruby on Rails. So this is simply going over the basics.'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
        
    end
    def new
        
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)
        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
        <nav class="navbar navbar-default">
            <div class="container">
              <ul class="navbar-nav mr-auto">
                <li><%= link_to "Home", home_path %></li>
              </ul>
              <ul class="navbar-nav mr-auto">
                <li><%= link_to "Create Post", new_post_path %></li>
              </ul>
            </div>
        </nav>
        <div class='container'>
            <%= yield %>
        </div>
  </body>
</html>

app/views/pages/about.html.erb
<h2><%= @title %></h2>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
        <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn -btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h2>Blog Posts</h2>
<% @posts.each do |post| %>
    <div class='well'>
        <h4><%= post.title %></h4>
        <p><%= post.body%></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-defult' %>
    </div
<% end %>

app/views/posts/new.html.erb
<h2>Add Post</h2>
<%= form_for :post, url: posts_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
        <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn -btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Are You Sure?'}, :class => 'btn btn-danger' %>